# Generated by Django 6.0.6 on 2026-06-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('representative_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('classification', models.CharField(choices=[('epc', 'EPC Engineering & System Construction Layouts'), ('solar', 'Commercial & Industrial Solar Grid Transitions'), ('audit', 'Statutory EPRA Class A Investment Energy Audits'), ('medical', 'Medical Asset Management & Clinical Infrastructure')], max_length=20)),
                ('scope_overview', models.TextField()),
                ('compliance_confirmed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Request For Quote',
                'verbose_name_plural': 'Requests For Quotes',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
